### ISSUE TITLE
stuck on startup, Web interface ready, https localhost 8443

### ISSUE THREAD

**Issue by aknyt** [andrepxx/go-dsp-guitar#8]
I'm stuck on start go-dsp-guitar. 
Downloaded binary package and decompress, Have started the Jack with cadence.
then excute in terminal:
```
$ ./dsp-linux-amd64
Web interface ready: https://localhost:8443/

```
Then stuck on this, Had to ctrl+c to cancel the program.

Please help! Thx.

**Comment by andrepxx** [comment]
I assume it's not "stuck". It is running and should show up in JACK as a client and process audio.

It does not have a "native" (for example GTK+ or Qt-based) UI, but a web-based UI - for two reasons.

* First, there is no well-maintained UI framework for Go.

* Second, splitting the UI into separate code / processes / languages (Go vs. JavaScript) forces us to have a clean interface between the actual application logic and the UI. There is even a network protocol for communication between them.

* Third, having a web-based UI allows the processing to be remote-controlled from another machine when opening the port (in this case 8443) on a firewall.

It is not uncommon in the Unix world for UI and "application logic" to be separate processes - and in this case, you can use a web browser (for example Firefox or Chrome) as the "UI".

Navigate to the address shown on the console using a web browser to open the UI and control it.

**Comment by andrepxx** [comment]
I assume it's not "stuck". It is running and should show up in JACK as a client and process audio.

It does not have a "native" (for example GTK+ or Qt-based) UI, but a web-based UI - for three reasons.

* First, there is no well-maintained UI framework for Go.

* Second, splitting the UI into separate code / processes / languages (Go vs. JavaScript) forces us to have a clean interface between the actual application logic and the UI. There is even a network protocol for communication between them.

* Third, having a web-based UI allows the processing to be remote-controlled from another machine when opening the port (in this case 8443) on a firewall.

It is not uncommon in the Unix world for UI and "application logic" to be separate processes - and in this case, you can use a web browser (for example Firefox or Chrome) as the "UI".

Navigate to the address shown on the console using a web browser to open the UI and control it.

**Comment by aknyt** [comment]
> 

Thanks for your explaining details, and understand what you mean.
The software have already run up in my system, and I am using it.

I have a personal suggestion for this, Could it add a more definite description on the program startup in terminal?
like:
`Web interface ready, visit https://localhost:8443/ in your browser.`
or
`go-dsp-guitar already running, use your browser to visit: http://localhost:8443/`
